import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { loaders } from "@/data/loaders";
import { validateApiResponse } from "@/lib/error-handler";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalPageData = await loaders.getGlobalPageData();
  console.log(globalPageData);
  const data = validateApiResponse(globalPageData, "global page")
  const { header, footer } = data
  console.log(header, footer);
  const headerComponent = header ? <Header data={header} /> : null;
  const footerComponent = footer ? <Footer data={footer} /> : null;
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {headerComponent}
        {children}
        {footerComponent}
      </body>
    </html>
  );
}
